language: node_js
node_js:
  - "10.0"
before_script:
  - yarn linter
script:
  - yarn build
after_success:
  - yarn lh --perf=85 https://loving-golick-23af51.netlify.com
  - yarn bundlesize
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
