language: node_js
node_js:
  - "10.0"
script:
  - yarn build
after_script:
  - yarn linter
  - yarn coveralls
after_success:
  - yarn lh --perf=90 https://loving-golick-23af51.netlify.com
  - yarn bundlesize
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
