import {
  USER_REGISTER_REQUEST,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_FAILURE,
  register,
} from "./register";

import { LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAILURE, login } from "./login";

export {
  USER_REGISTER_REQUEST,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_FAILURE,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  register,
  login,
};
